FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Затем копируем весь проект
# COPY test-data/test.pdf /app/test.pdf
COPY . .


# Собираем бинарник
RUN go build -o /app/sender ./cmd/sender-service/main.go

CMD ["/app/sender"]
