FROM golang:1.23-alpine

WORKDIR /app

# Сначала копируем go.mod и go.sum для кэширования зависимостей
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Затем копируем весь проект
COPY . .

# Собираем бинарник
RUN go build -o /app/sender ./cmd/sender-service/main.go

CMD ["/app/sender"]
