services:
  sender-service:
    build:
      context: .
      dockerfile: Dockerfile.sender
    container_name: sender-service
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - GIN_MODE=release

  status-receiver:
    build:
      context: .
      dockerfile: Dockerfile.receiver
    container_name: status-receiver
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    environment:
      - GIN_MODE=release
